language: java
cache:
  directories:
  - $HOME/.m2
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode7.3
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq exuberant-ctags cvs git mercurial cssc bzr subversion monotone rcs pep8; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ./scripts/install-bitkeeper.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ctags cvs monotone; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pep8; fi
install: true

before_script:
 - if `which bk`; then bk --version; fi
 - if `which hg`; then hg --version; fi
 - if `which git`; then git --version; fi
 - if `which svn`; then svn --version; fi
 - if `which cvs`; then cvs --version; fi
 - if `which mtn`; then mtn --version; fi
 - if `which bzr`; then bzr version; fi
 # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd opengrok-indexer && mvn javadoc:javadoc && cd ../opengrok-web && mvn javadoc:javadoc && cd ..; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "O_cda5pWDBAP-O3_0nG5RQ"

#
# If compilation fails, we do not want to run the tests. Travis runs everything
# in 'script' no matter if an individual command fails or not. This kludgy
# looking shell incantation takes care of that.
#
script: "mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V compile \
             && mvn verify -B"

addons:
  coverity_scan:
    project:
      name: "OpenGrok/OpenGrok"
      description: "Build submitted via Travis CI"
      branch_pattern: "coverity_scan"
      #    build_command_prepend: "mvn clean"
      build_command: "mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V compile"

deploy:
  # Pre-release
  - provider: releases
    script:
    - echo "$TRAVIS_TAG"
    - echo "$TRAVIS_BRANCH"
    - mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V package
    prerelease: true
    api_key:
      secure: sCPR3INSECAj3VcIr2eKVOfWVs4mJbOe9WLVrnV0zo9ITRsSFxvjOPbtlQVcr3kQSlYfPsw4EqWcZMXe7usGOlBqKPd8eipce0QFo7sZbeOFHwBO5VHvtiaeyeGnDSmxfpjgwHvUkIQ8hc2EAbJ/sx8qtg+bfcLobiiW4xcCzc+j1Tbjv84CO46m7GiV3ZW63yB/q/5MCxqUOwd2A4FnN5vKS03SLklNra1iuTJzi9jhcN0I+Y9rzwLDzkNQnZhC0nlVgks1AMtv/DCK5a3hYrzXU5x3mHZ2r+qMfWaXQ081odQctzs5JciJrtbm18H9esPNKKLiHmn6d8HjXR5g65VPoJZnj/gTrldGSKX+dQPJWAFTrf2R8zcKlBMtkLpJQKNmsoYBbXAyvlxTQshWDOeVRmyNB0HZwPHb3vfnqfXWFYi7f3+3hnV41m111huZ+8EdVcNbPAddlKvzaJ09sXbmNzSKduaF+f+BGfRMmBT+3eyOLQXPY3++nMeJ1BRxL78OWCeqDVi+jxSbdSNIo7bvo2NK3FVWMEanGpEKdJgbR8N+PPL+0VRTziYNtHQ7j1W2QmIs0YRF93f2TrnY4qj9CUMcm+qcLnRtcWtK6gHBxe93ojosn6pTZNTgOWgHyQDXiksevUyIvs80AtVEGNFgkj4WAbFRtWiMeRgTgZQ=
    file: distribution/target/opengrok-$TRAVIS_TAG.tar.gz
    skip_cleanup: true
    on:
      # XXX
      repo: vladak/OpenGrok
      tags: true
      condition: "$TRAVIS_TAG =~ rc[0-9]+$"
      # XXX branch: master
  # Full release
  - provider: releases
    script:
    - echo "$TRAVIS_TAG"
    - echo "$TRAVIS_BRANCH"
    - mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V package
    api_key:
      secure: sCPR3INSECAj3VcIr2eKVOfWVs4mJbOe9WLVrnV0zo9ITRsSFxvjOPbtlQVcr3kQSlYfPsw4EqWcZMXe7usGOlBqKPd8eipce0QFo7sZbeOFHwBO5VHvtiaeyeGnDSmxfpjgwHvUkIQ8hc2EAbJ/sx8qtg+bfcLobiiW4xcCzc+j1Tbjv84CO46m7GiV3ZW63yB/q/5MCxqUOwd2A4FnN5vKS03SLklNra1iuTJzi9jhcN0I+Y9rzwLDzkNQnZhC0nlVgks1AMtv/DCK5a3hYrzXU5x3mHZ2r+qMfWaXQ081odQctzs5JciJrtbm18H9esPNKKLiHmn6d8HjXR5g65VPoJZnj/gTrldGSKX+dQPJWAFTrf2R8zcKlBMtkLpJQKNmsoYBbXAyvlxTQshWDOeVRmyNB0HZwPHb3vfnqfXWFYi7f3+3hnV41m111huZ+8EdVcNbPAddlKvzaJ09sXbmNzSKduaF+f+BGfRMmBT+3eyOLQXPY3++nMeJ1BRxL78OWCeqDVi+jxSbdSNIo7bvo2NK3FVWMEanGpEKdJgbR8N+PPL+0VRTziYNtHQ7j1W2QmIs0YRF93f2TrnY4qj9CUMcm+qcLnRtcWtK6gHBxe93ojosn6pTZNTgOWgHyQDXiksevUyIvs80AtVEGNFgkj4WAbFRtWiMeRgTgZQ=
    file: distribution/target/opengrok-$TRAVIS_TAG.tar.gz
    skip_cleanup: true
    on:
      # XXX
      repo: vladak/OpenGrok
      tags: true
      condition: "! $TRAVIS_TAG =~ rc[0-9]+$"
      # XXX branch: master
