#!/bin/bash

if [[ "$RUNNER_OS" == "Linux" ]]; then
	if ! sudo apt-get update -qq; then
		echo "cannot update"
		exit 1
	fi

	if ! sudo apt-get install -qq \
	    cvs \
	    mercurial \
	    cssc \
	    bzr \
	    subversion \
	    rcs \
	    rcs-blame \
	    python3 \
	    python3-venv \
	    python3-pip \
	    nodejs \
	    jq; then
		echo "cannot install extra packages"
		exit 1
	fi

	# Bitkeeper install failure is not critical, so exit code is not checked.
	sudo ./dev/install-bitkeeper.sh

	if ! sudo ./dev/install-universal_ctags.sh; then
		echo "cannot install Universal ctags"
		exit 1
	fi

elif [[ "$RUNNER_OS" == "macOS" ]]; then
        export HOMEBREW_NO_AUTO_UPDATE=1

	if ! brew install cvs libgit2 jq autoconf automake mercurial perforce; then
		echo "cannot install extra packages"
		exit 1
	fi

	if ! 	sudo ./dev/install-universal_ctags.sh; then
		echo "cannot install Universal ctags"
		exit 1
	fi
fi
